api:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin