<?php

namespace ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
    public function findAllOrderByName()
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->orderBy('o.name', 'ASC');

        return $queryBuilder->getQuery()
            ->getArrayResult();
    }

    public function findById($id)
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->where('o.id = :id')
            ->setParameter('id', $id);

        return $queryBuilder->getQuery()
            ->getOneOrNullResult(Query::HYDRATE_ARRAY);
    }
}
