<?php

namespace ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PointLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointLocationRepository extends EntityRepository
{
    public function findValidPoint($long, $lat)
    {
        return 1;
    }

    public function findValidPoints($long, $lat)
    {
        return [
            [
                'id' => 1,
                'name' => 'test',
                'description' => 'test',
                'location' => [
                    'long' => 1,
                    'lat' => 1
                ]
            ]
        ];
    }
}
