services:
    sonata.admin.post:
        class: Acme\DemoBundle\Admin\PointsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Points", label: "Points" }
        arguments:
            - ~
            - ApiBundle\Entity\Points
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]

    sonata.admin.organization:
        class: Acme\DemoBundle\Admin\OrganizationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Points", label: "Organizations" }
        arguments:
            - ~
            - ApiBundle\Entity\Organization
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]